// ═══════════════════════════════════════════════════════════════════════════
// SPECIES DATABASE
// ═══════════════════════════════════════════════════════════════════════════

const SPECIES_DB = {
    "levrek": {
        name: "Levrek", nameEn: "European Sea Bass", icon: "🐟", scientificName: "Dicentrarchus labrax",
        photoId: 1,
        category: "KIYI_AVCI",
        peakHours: "DAWN_DUSK", peakHoursDesc: "Şafak ve gün batımı ±2 saat",
        tempRange: { min: 12, opt: 18, max: 25 },
        seasons: { winter: 0.85, spring: 0.55, summer: 0.25, autumn: 0.80 },
        activity: "DAWN_DUSK",
        pressureSensitivity: 0.8,
        wavePref: 0.9,
        clarityPref: "TURBID",
        currentPref: 0.6,
        salinityPref: "MEDIUM",
        planktonPref: "MEDIUM",
        moonPref: "dark",
        sstTrendPref: "warming",
        regions: ["MARMARA", "EGE", "AKDENİZ"],
        depth: { min: 1, opt: 8, max: 40 },
        advice: { bait: "Canlı Teke, Mamun, Boru Kurdu", lure: "WTD, 10-14cm Maket, Silikon", rig: "Gezer Kurşunlu Dip, Spin", hook: "1/0 - 4/0 Geniş Pala" },
        legalSize: "25 cm",
        note: "Köpüklü, bulanık suyu sever. Gürültüden kaçının. Vicdani limit 40 cm."
    },
    "lufer": {
        name: "Lüfer/Kofana", nameEn: "Bluefish", icon: "🦈", scientificName: "Pomatomus saltatrix",
        photoId: 2,
        category: "PELAJIK",
        shoreMonths: [8, 9, 10, 11], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAWN_DUSK", peakHoursDesc: "Sabah suyu ve akşam suyu",
        tempRange: { min: 12, opt: 18, max: 25 },
        seasons: { winter: 0.50, spring: 0.20, summer: 0.15, autumn: 0.95 },
        monthlyActivity: [0.45, 0.4, 0.25, 0.2, 0.2, 0.15, 0.15, 0.2, 0.65, 0.95, 0.9, 0.55],
        migrationBonus: {
        "KARADENİZ": { months: [4,5,6],    bonus: 0.25 },
        "MARMARA":   { months: [9,10,11],  bonus: 0.35 },
        "EGE":       { months: [10,11],    bonus: 0.20 }
    },
        activity: "DAWN_DUSK",
        pressureSensitivity: 0.9,
        wavePref: 0.6,
        clarityPref: "CLEAR",
        currentPref: 0.85,
        salinityPref: "MEDIUM",
        planktonPref: "HIGH",
        moonPref: "bright",  // BİYOLOJİK DÜZELTİ: Dolunayda avları (istavrit, çaça) yüzeye çıkar; Lüfer derinde yoğun beslenır — "dark" efsanesi balıkçı miti
        sstTrendPref: "cooling",
        regions: ["MARMARA", "EGE", "KARADENİZ"],
        depth: { min: 1, opt: 8, max: 40 },
        advice: { bait: "Yaprak Zargana, İstavrit Fleto", lure: "Kaşık, Ağır Rapala, Poşhter", rig: "Uzun Olta, Mantarlı Çinekop, Hırsızlı Zoka", hook: "1 - 4/0 Uzun Pala + Çelik Tel" },
        legalSize: "20 cm",
        note: "20cm altı (Defne Yaprağı) bırakın. Çelik tel zorunlu — keskin dişler misina keser."
    },
    "eskina": {
        name: "Eşkina", nameEn: "Brown Meagre", icon: "🐟", scientificName: "Sciaena umbra",
        photoId: 3,
        category: "KIYI_AVCI",
        peakHours: "NIGHT", peakHoursDesc: "22:00 - 03:00 arası en aktif",
        tempRange: { min: 12, opt: 18, max: 25 },
        seasons: { winter: 0.30, spring: 0.75, summer: 0.80, autumn: 0.40 },
        activity: "NIGHT",
        pressureSensitivity: 0.6,
        wavePref: 0.5,
        clarityPref: "MODERATE",
        currentPref: 0.3,
        salinityPref: "ANY",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 1, opt: 8, max: 40 },
        advice: { bait: "Canlı Teke (Gece), Yengeç", lure: "Silikon Karides (LRF)", rig: "Şamandıralı (Starlight), Dip Bırakma", hook: "1 - 3" },
        legalSize: "Yok (5 adet/gün)",
        note: "Zifiri karanlıkta avlanır. Fosforlu şamandıra şart."
    },
    "minekop": {
        name: "Minekop", nameEn: "Meagre", icon: "🐟", scientificName: "Argyrosomus regius",
        photoId: 4,
        category: "KIYI_AVCI",
        peakHours: "NIGHT", peakHoursDesc: "Gece ve alacakaranlık",
        tempRange: { min: 12, opt: 18, max: 25 },
        seasons: { winter: 0.40, spring: 0.60, summer: 0.50, autumn: 0.70 },
        activity: "NIGHT",
        pressureSensitivity: 0.7,
        wavePref: 0.8,
        clarityPref: "TURBID",
        currentPref: 0.5,
        salinityPref: "MEDIUM",
        regions: ["EGE", "AKDENİZ"],
        depth: { min: 1, opt: 8, max: 40 },
        advice: { bait: "Boru Kurdu, Sülünez, Sardalya", lure: "Silikon Yemler", rig: "Ağır Dip Takımı", hook: "1/0 - 2/0" },
        legalSize: "Yok (5kg/gün)",
        note: "Gece ve alacakaranlıkta aktif. Çalkantılı suyu sever."
    },
    "ispendek": {
    name: "İspendek", nameEn: "Picarel", icon: "🐟", scientificName: "Spicara smaris",
    photoId: 9,
    category: "KIYI",
    peakHours: "DAY", peakHoursDesc: "Gündüz aktif, sabah erken ve akşamüstü zirve",
    tempRange: { min: 13, opt: 19, max: 25 },
    seasons: { winter: 0.30, spring: 0.70, summer: 0.90, autumn: 0.60 },
    activity: "DAY",
    pressureSensitivity: 0.3,
    wavePref: 0.3,
    clarityPref: "CLEAR",
    currentPref: 0.4,
    salinityPref: "HIGH",
    regions: ["EGE", "AKDENİZ", "MARMARA"],
    depth: { min: 5, opt: 25, max: 100 },
    advice: { bait: "Ekmek İçi, Küçük Solucan, Midye", lure: "Micro Jig, Küçük Kaşık", rig: "Çoklu İğneli Takım, Şamandıralı", hook: "No:8-12 Olta İğnesi" },
    legalSize: "11 cm",
    note: "Sürü halinde gezer. Çoğunlukla tabana yakın dolaşır. Küçük yem ve ince misina verimi artırır. Yazın kıyıya yaklaşır."

},
    "cipura": {
        name: "Çipura", nameEn: "Gilt-head Bream", icon: "🐠", scientificName: "Sparus aurata",
        photoId: 11,
        category: "KIYI",
        peakHours: "DAY", peakHoursDesc: "Sabah 08:00-11:00, İkindi 15:00-17:00",
        tempRange: { min: 14, opt: 20, max: 28 },
        seasons: { winter: 0.35, spring: 0.60, summer: 0.50, autumn: 0.85 },
        activity: "DAY",
        pressureSensitivity: 0.4,
        wavePref: 0.3,
        clarityPref: "MODERATE",
        currentPref: 0.3,
        salinityPref: "MEDIUM",
        planktonPref: "MEDIUM",
        sstTrendPref: "warming",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 0, opt: 10, max: 150 },
        advice: { bait: "Canlı Mamun, Yengeç, Midye", lure: "Micro Jig, Rubber", rig: "Hırsızlı Dip Takımı", hook: "Chinu No:2-4" },
        legalSize: "20 cm",
        note: "Yemi önce ezer, hemen tasmalama. Sabırlı ol."
    },
    "karagoz": {
        name: "Karagöz", nameEn: "Common Two-banded Bream", icon: "🐟", scientificName: "Diplodus vulgaris",
        photoId: 12,
        category: "KIYI",
        peakHours: "DAWN_DUSK", peakHoursDesc: "Sabah ve akşam suyu",
        tempRange: { min: 12, opt: 20, max: 25 },
        seasons: { winter: 0.75, spring: 0.50, summer: 0.35, autumn: 0.80 },
        activity: "DAWN_DUSK",
        pressureSensitivity: 0.6,
        wavePref: 0.9,
        clarityPref: "TURBID",
        currentPref: 0.5,
        salinityPref: "MEDIUM",
        planktonPref: "MEDIUM",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 0, opt: 10, max: 160 },
        advice: { bait: "Mamun, Yengeç, Madya", lure: "Silikon Karides (Nadir)", rig: "Şeytan Oltası, Tek İğneli Dip", hook: "2 - 5 Sağlam Dövme" },
        legalSize: "18 cm",
        note: "Kayalık, köpüklü sularda. Misina sürtünmesine dikkat."
    },
    "mirmir": {
        name: "Mırmır", nameEn: "Striped Seabream", icon: "🦓", scientificName: "Lithognathus mormyrus",
        photoId: 13,
        category: "KIYI",
        peakHours: "NIGHT", peakHoursDesc: "Gece kıyıya yaklaşır, 21:00-02:00",
        tempRange: { min: 14, opt: 18, max: 24 },
        seasons: { winter: 0.25, spring: 0.55, summer: 0.85, autumn: 0.70 },
        activity: "NIGHT",
        pressureSensitivity: 0.5,
        wavePref: 0.7,
        clarityPref: "TURBID",
        currentPref: 0.4,
        salinityPref: "MEDIUM",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 0, opt: 10, max: 150 },
        advice: { bait: "Boru Kurdu (Favori), Mamun, Kum Solucanı", lure: "Kokulu Silikon (Kurt/Yengeç)", rig: "Hafif Gezer Kurşunlu Dip", hook: "4 - 6 İnce Pala" },
        legalSize: "20 cm (Etik)",
        note: "Gece kıyıya 1m'ye kadar yaklaşır. Işık tutmayın!"
    },
    "kalamar": {
        name: "Kalamar", nameEn: "European Squid", icon: "🦑", scientificName: "Loligo vulgaris",
        photoId: 46,
        category: "KAFADANBACAKLI",
        peakHours: "NIGHT", peakHoursDesc: "Gece, özellikle ay ışığında",
        tempRange: { min: 14, opt: 19, max: 24 },
        seasons: { winter: 0.55, spring: 0.40, summer: 0.10, autumn: 0.70 },
        activity: "NIGHT",
        pressureSensitivity: 0.5,
        wavePref: 0.2,
        clarityPref: "CLEAR",
        currentPref: 0.2,
        salinityPref: "HIGH",  // Açık deniz türü — yüksek tuzluluğu tercih eder,
        planktonPref: "LOW",
        moonPref: "bright",
        sstTrendPref: "stable",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 2, opt: 20, max: 150 },
        advice: { bait: "Yok", lure: "Kalamar Zokası (Renkli/Fosforlu)", rig: "Zoka At-Çek (Whipping)", hook: "Özel Zoka İğnesi" },
        legalSize: "Yok",
        note: "Berrak su ve ay ışığında. Yaz başı üreme dönemi, avlamayın."
    },
    "ahtapot": {
        name: "Ahtapot", nameEn: "Common Octopus", icon: "🐙", scientificName: "Octopus vulgaris",
        photoId: 47,
        category: "KAFADANBACAKLI",
        peakHours: "DAY", peakHoursDesc: "Gündüz aktif, sabah saatleri",
        tempRange: { min: 14, opt: 19, max: 24 },
        seasons: { winter: 0.65, spring: 0.50, summer: 0.30, autumn: 0.55 },
        activity: "DAY",
        pressureSensitivity: 0.5,
        wavePref: 0.1,
        clarityPref: "MODERATE",
        currentPref: 0.1,
        salinityPref: "HIGH",  // Kayalık-açık deniz türü — yüksek tuzluluğu tercih eder,
        planktonPref: "LOW",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 2, opt: 20, max: 150 },
        advice: { bait: "Yengeç, Tavuk But", lure: "Ahtapot Zokası, Plastik Yengeç", rig: "Çarpmalı Zoka", hook: "Özel Zoka" },
        legalSize: "1 kg",
        note: "Yemi sarıp yapışır. Ağırlık hissedince sert tasma."
    },

    "kikla": {
        name: "Kikla-Ot Balığı", nameEn: "Ballan Wrasse", icon: "🐟", scientificName: "Labrus bergylta",
        photoId: 74,
        category: "KAYALIK",
        peakHours: "DAY", peakHoursDesc: "Gündüz aktif, özellikle sabah erken ve akşamüstü",
        tempRange: { min: 12, opt: 17, max: 22 },
        seasons: { winter: 0.30, spring: 0.65, summer: 0.80, autumn: 0.70 },
        activity: "DAY",
        pressureSensitivity: 0.4,
        wavePref: 0.6,
        clarityPref: "CLEAR",
        currentPref: 0.5,
        salinityPref: "HIGH",
        regions: ["EGE", "AKDENİZ"],
        depth: { min: 1, opt: 10, max: 50 },
        advice: { bait: "Karides, Yengeç, Midye", lure: "LRF Silikon, Micro Jig", rig: "Dip Takımı, LRF", hook: "4 - 1 Güçlü" },
        legalSize: "Yasal limit yok",
        note: "Kayalık ve yosunluk bölgelerde yaşayan güçlü bir dip balığıdır. Kabukluları kırabilecek güçlü çenesi vardır."
    },
    
    "istavrit": {
        name: "İstavrit", nameEn: "Horse Mackerel", icon: "🐟", scientificName: "Trachurus mediterraneus",
        photoId: 23,
        category: "PELAJIK",
        shoreMonths: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "ALL", peakHoursDesc: "Tüm gün aktif, sabah/akşam yoğun",
        tempRange: { min: 10, opt: 18, max: 24 },
        seasons: { winter: 0.60, spring: 0.80, summer: 0.75, autumn: 0.85 },
        monthlyActivity: [0.55, 0.5, 0.65, 0.75, 0.85, 0.9, 0.85, 0.85, 0.85, 0.8, 0.7, 0.6],
        migrationBonus: {
        "KARADENİZ": { months: [4,5,6,7],  bonus: 0.20 },
        "EGE":       { months: [3,4,10,11],bonus: 0.15 }
    },
        activity: "ALL",
        pressureSensitivity: 0.5,
        wavePref: 0.5,
        clarityPref: "ANY",
        currentPref: 0.7,
        salinityPref: "MEDIUM",
        planktonPref: "HIGH",
        moonPref: "bright",
        sstTrendPref: "any",
        regions: ["MARMARA", "EGE", "KARADENİZ", "AKDENİZ"],
        depth: { min: 5, opt: 20, max: 250 },
        advice: { bait: "Karides Parçası, Tavuk Göğsü", lure: "Çapari, LRF Silikon, Micro Jig", rig: "Çapari, LRF", hook: "9 - 12 İnce" },
        legalSize: "13 cm",
        note: "Sürü halinde. Çapari ile kova doldurulur."
    },
    "barbun": {
        name: "Barbun", nameEn: "Red Mullet", icon: "🐟", scientificName: "Mullus barbatus",
        photoId: 33,
        category: "DIP_DERIN",
        shoreMonths: [], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAY", peakHoursDesc: "Gündüz, çamurlu/kumlu dip",
        tempRange: { min: 12, opt: 18, max: 24 },
        seasons: { winter: 0.80, spring: 0.60, summer: 0.30, autumn: 0.70 },
        activity: "DAY",
        pressureSensitivity: 0.5,
        wavePref: 0.5,
        clarityPref: "ANY",
        currentPref: 0.3,
        salinityPref: "HIGH",
        sstTrendPref: "stable",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 10, opt: 80, max: 300 },
        advice: { bait: "Karides, Kurt, Midye, Tavuk Göğsü", lure: "Genelde Yok", rig: "Üçlü Dip Oltası", hook: "9 - 11 İnce Telli" },
        legalSize: "13 cm",
        note: "Yumuşak dudak yapısı var — ince telli küçük iğne (9-11 no) şart. Yemi emerek alır."
    },
    "iskorpit": {
        name: "İskorpit", nameEn: "Scorpionfish", icon: "🐟", scientificName: "Scorpaena porcus",
        photoId: 40,
        category: "DIP_KIYI",
        peakHours: "NIGHT", peakHoursDesc: "Gece aktif, 21:00 sonrası",
        tempRange: { min: 10, opt: 18, max: 24 },
        seasons: { winter: 0.60, spring: 0.55, summer: 0.50, autumn: 0.65 },
        activity: "NIGHT",
        pressureSensitivity: 0.5,
        wavePref: 0.5,
        clarityPref: "ANY",
        currentPref: 0.3,
        salinityPref: "MEDIUM",
        regions: ["EGE", "AKDENİZ", "MARMARA", "KARADENİZ"],
        depth: { min: 0, opt: 20, max: 200 },
        advice: { bait: "İstavrit Fleto, Karides", lure: "Kokulu Silikonlar (LRF)", rig: "Dip Takımı, LRF", hook: "4 - 6 Uzun Pala" },
        legalSize: "Yok",
        note: "⚠️ DİKENLERİ ZEHİRLİ! Dikkatli olun."
    },

    "trakun": {
    name: "Trakun (Tral)", nameEn: "Blue Runner", icon: "🐟", scientificName: "Caranx crysos",
    photoId: 73,
    category: "PELAJIK",
        shoreMonths: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], // kıyıya yaklaşma ayları (0=Ocak)
    peakHours: "DAY", peakHoursDesc: "Sabah ve öğleden sonra sürü halinde aktif",
    tempRange: { min: 17, opt: 25, max: 28 },
    seasons: { winter: 0.20, spring: 0.55, summer: 0.95, autumn: 0.70 },
    activity: "DAY",
    pressureSensitivity: 0.3,
    wavePref: 0.5,
    clarityPref: "CLEAR",
    currentPref: 0.6,
    salinityPref: "HIGH",
    planktonPref: "HIGH",
    sstTrendPref: "WARMING",
    regions: ["EGE", "AKDENİZ"],
    depth: { min: 0, opt: 20, max: 50 },
    advice: { bait: "Hamsi, İstavrit", lure: "Metal Kaşık, Jig", rig: "Paternoster, Trolling", hook: "2 - 4" },
    legalSize: "18 cm",
    note: "Sürü halinde yüzer. Yaz aylarında Ege ve Akdeniz kıyılarında yoğun."
},
    "kefal": {
        name: "Kefal", nameEn: "Flathead Grey Mullet", icon: "🐟", scientificName: "Mugil cephalus",
        photoId: 44,
        category: "LAGUN",
        peakHours: "DAY", peakHoursDesc: "Sabah erken ve ikindi saatleri",
        tempRange: { min: 10, opt: 18, max: 28 },
        seasons: { winter: 0.40, spring: 0.70, summer: 0.85, autumn: 0.65 },
        activity: "DAY",
        pressureSensitivity: 0.4,
        wavePref: 0.4,
        clarityPref: "TURBID",
        currentPref: 0.3,
        salinityPref: "LOW",  // Lagün türü — düşük/acı tuzlu suyu tercih eder,
        planktonPref: "MEDIUM",
        sstTrendPref: "any",
        regions: ["MARMARA", "EGE", "AKDENİZ", "KARADENİZ"],
        depth: { min: 0, opt: 5, max: 15 },
        advice: { bait: "Ekmek İçi, Kıbrıs Sarma", lure: "Yok", rig: "Kıbrıs Takımı, Şamandıralı", hook: "6 - 9" },
        legalSize: "20 cm",
        note: "Lagün ve nehir ağızlarında. Düşük tuzluluğu sever."
    },
    "zargana": {
        name: "Zargana", nameEn: "Garfish", icon: "🐟", scientificName: "Belone belone",
        photoId: 20,
        category: "KIYI",
        peakHours: "DAY", peakHoursDesc: "Güneşli günlerde yüzeyde",
        tempRange: { min: 12, opt: 18, max: 25 },
        seasons: { winter: 0.20, spring: 0.60, summer: 0.80, autumn: 0.50 },
        activity: "DAY",
        pressureSensitivity: 0.5,
        wavePref: 0.2,
        clarityPref: "CLEAR",
        currentPref: 0.4,
        salinityPref: "ANY",
        planktonPref: "MEDIUM",
        moonPref: "bright",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 1, opt: 8, max: 40 },
        advice: { bait: "Kurt, Fleto Balık", lure: "İpek (Turuncu)", rig: "Şamandıralı Top, İpek", hook: "6 - 10 İnce" },
        legalSize: "Yok",
        note: "Güneşli havalarda yüzeyde. Berrak su sever."
    },
    // ═══════════════════════════════════════════════════════════════════════════
    // YENİ TÜRLER - FishBase & FAO Referansları
    // ═══════════════════════════════════════════════════════════════════════════
    "orfoz": {
        name: "Orfoz", nameEn: "Dusky Grouper", icon: "🐟", scientificName: "Epinephelus marginatus",
        photoId: 5,
        category: "KORUMA",
        peakHours: "DAWN_DUSK", peakHoursDesc: "BİLGİ AMAÇLI — avlanması kesinlikle yasaktır",
        tempRange: { min: 14, opt: 20, max: 26 },
        seasons: { winter: 0.00, spring: 0.00, summer: 0.00, autumn: 0.00 },
        activity: "DAWN_DUSK",
        pressureSensitivity: 0.5,
        wavePref: 0.4,
        clarityPref: "CLEAR",
        currentPref: 0.3,
        salinityPref: "HIGH",
        sstTrendPref: "stable",
        protected: true,
        regions: ["EGE", "AKDENİZ"],
        depth: { min: 5, opt: 30, max: 200 },
        advice: { bait: "-", lure: "-", rig: "-", hook: "-" },
        legalSize: "YASAK",
        note: "🚫 AVLANMASI KESİNLİKLE YASAKTIR. IUCN Tehlike Altında (Endangered). 6/2 Numaralı Tebliğ. Görürsen bırak."
    },
    "akya": {
        name: "Akya", nameEn: "Greater Amberjack", icon: "🐟", scientificName: "Seriola dumerili",
        photoId: 6,
        category: "PELAJIK",
        shoreMonths: [6, 7, 8, 9], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAY", peakHoursDesc: "Gündüz akıntılı burun başları, 24°C üzeri",
        tempRange: { min: 14, opt: 22, max: 28 },
        seasons: { winter: 0.30, spring: 0.60, summer: 0.90, autumn: 0.75 },
        activity: "DAY",
        pressureSensitivity: 0.7,
        wavePref: 0.5,
        clarityPref: "CLEAR",
        currentPref: 0.8,
        salinityPref: "HIGH",
        planktonPref: "HIGH",
        moonPref: "dark",
        regions: ["EGE", "AKDENİZ"],
        depth: { min: 10, opt: 50, max: 300 },
        advice: { bait: "Canlı İstavrit, Sardalya", lure: "Popper, Stickbait, Metal Jig", rig: "Trolling, Jigging, Popping", hook: "3/0 - 6/0 + Çelik Tel" },
        legalSize: "30 cm",
        note: "Güçlü avcı! Tekne gerektirir. Yaz aylarında açıklarda bollaşır."
    },
    "sinarit": {
        name: "Sinarit", nameEn: "Common Dentex", icon: "🐟", scientificName: "Dentex dentex",
        photoId: 7,
        category: "KIYI_AVCI",
        peakHours: "DAY", peakHoursDesc: "Gündüz kayalık dipte, bahar üreme döneminde sürüleşir",
        tempRange: { min: 13, opt: 18, max: 22 },
        seasons: { winter: 0.45, spring: 0.70, summer: 0.80, autumn: 0.65 },
        activity: "DAY",
        pressureSensitivity: 0.6,
        wavePref: 0.5,
        clarityPref: "MODERATE",
        currentPref: 0.5,
        salinityPref: "HIGH",
        planktonPref: "MEDIUM",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 15, opt: 30, max: 50 },
        advice: { bait: "Canlı Kalamar, Sübye, Karides", lure: "Metal Jig, Maket Balık", rig: "Jigging, Dip Sırtısı, Trolling", hook: "2/0 - 5/0" },
        legalSize: "35 cm",
        note: "Denizlerin padişahı. Kayalık dip sever. legalSize 35cm — bilimsel referans."
    },
    "mercan": {
        name: "Mercan", nameEn: "Red Porgy", icon: "🐟", scientificName: "Pagrus pagrus",
        photoId: 35,
        category: "DIP_KIYI",
        peakHours: "DAY", peakHoursDesc: "Gündüz, kayalık ve kumlu karışık dipte",
        tempRange: { min: 14, opt: 20, max: 26 },
        seasons: { winter: 0.40, spring: 0.60, summer: 0.65, autumn: 0.85 },
        activity: "DAY",
        pressureSensitivity: 0.5,
        wavePref: 0.35,
        clarityPref: "MODERATE",
        currentPref: 0.4,
        salinityPref: "MEDIUM",
        planktonPref: "MEDIUM",
        sstTrendPref: "stable",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 10, opt: 60, max: 250 },
        advice: { bait: "Karides, Kalamar, Midye, Sülünez", lure: "Jig, Silikon", rig: "Dip Takımı", hook: "2 - 6" },
        legalSize: "18 cm",
        note: "Kayalık-kumluk karışık dipte gezer. Yem dibe oturmalı. Hafif akıntıda daha istekli vurur."
    },
    "antenli_mercan": {
        name: "Antenli Mercan", nameEn: "Blackspot Seabream", icon: "🐟", scientificName: "Pagellus bogaraveo",
        photoId: 36,
        category: "DIP_DERIN",
        shoreMonths: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAY", peakHoursDesc: "Gündüz, derin kayalık dipte",
        tempRange: { min: 10, opt: 16, max: 22 },
        seasons: { winter: 0.70, spring: 0.60, summer: 0.40, autumn: 0.65 },
        activity: "DAY",
        pressureSensitivity: 0.4,
        wavePref: 0.3,
        clarityPref: "ANY",
        currentPref: 0.3,
        salinityPref: "MEDIUM",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 50, opt: 150, max: 700 },
        advice: { bait: "Karides, Kurt, Kalamar", lure: "Yok", rig: "Derin Su Dip Takımı", hook: "4 - 8" },
        legalSize: "Yok",
        note: "⚠️ Derin suda (50-700m). Tekne ile parakete avı."
    },

    "lipsoz": {
    name: "Lipsoz", nameEn: "Red Scorpionfish", icon: "🐟", scientificName: "Scorpaena scrofa",
    photoId: 84,
    category: "DIP_KIYI",
    peakHours: "NIGHT", peakHoursDesc: "Gece aktif, pusu kurarak avlanır",
    tempRange: { min: 11, opt: 15, max: 18 },
    seasons: { winter: 0.65, spring: 0.70, summer: 0.55, autumn: 0.75 },
    activity: "NIGHT",
    pressureSensitivity: 0.5,
    wavePref: 0.4,
    clarityPref: "MODERATE",
    currentPref: 0.4,
    salinityPref: "HIGH",
    regions: ["EGE", "AKDENİZ", "MARMARA"],
    depth: { min: 20, opt: 60, max: 150 },
    advice: { bait: "İstavrit Fleto, Karides, Kalamar", lure: "Kokulu Silikon (LRF)", rig: "Dip Takımı", hook: "2/0 - 4/0" },
    legalSize: "15 cm",
    note: "⚠️ DİKENLERİ ZEHİRLİ! Karadeniz'de bulunmaz. Kayalık ve taşlık diplerde pusu kurar. Yazın sığ kıyılara yaklaşır."
},
    "melanur": {
        name: "Melanur", nameEn: "Saddled Seabream", icon: "🐟", scientificName: "Oblada melanura",
        photoId: 15,
        category: "KIYI",
        peakHours: "DAY", peakHoursDesc: "Gündüz, sığ kayalık alanlarda",
        tempRange: { min: 14, opt: 20, max: 26 },
        seasons: { winter: 0.40, spring: 0.65, summer: 0.80, autumn: 0.60 },
        activity: "DAY",
        pressureSensitivity: 0.4,
        wavePref: 0.4,
        clarityPref: "CLEAR",
        currentPref: 0.3,
        salinityPref: "MEDIUM",
        planktonPref: "MEDIUM",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 1, opt: 15, max: 40 },
        advice: { bait: "Ekmek, Midye, Kurt", lure: "Micro Jig", rig: "Şamandıralı, LRF", hook: "8 - 12" },
        legalSize: "Yok",
        note: "Kuyruk sapındaki siyah benekle tanınır. Kayalık sever."
    },
    "kupes": {
        name: "Kupes/Mandagöz", nameEn: "Bogue", icon: "🐟", scientificName: "Boops boops",
        photoId: 16,
        category: "KIYI",
        peakHours: "DAY", peakHoursDesc: "Gündüz, sürü halinde yüzey yakını",
        tempRange: { min: 12, opt: 18, max: 24 },
        seasons: { winter: 0.50, spring: 0.70, summer: 0.75, autumn: 0.65 },
        activity: "DAY",
        pressureSensitivity: 0.4,
        wavePref: 0.3,
        clarityPref: "MODERATE",
        currentPref: 0.4,
        salinityPref: "MEDIUM",
        regions: ["EGE", "AKDENİZ", "MARMARA", "KARADENİZ"],
        depth: { min: 1, opt: 20, max: 100 },
        advice: { bait: "Ekmek, Hamur, Kurt", lure: "Çapari", rig: "Çapari, Şamandıralı", hook: "10 - 14" },
        legalSize: "Yok",
        note: "Sürü halinde. Çapari ile bol av. Canlı yem olarak kullanılır."
    },
    "sivriburun": {
        name: "Sivriburun", nameEn: "Sharpsnout Seabream", icon: "🐟", scientificName: "Diplodus puntazzo",
        photoId: 17,
        category: "KIYI",
        peakHours: "DAWN_DUSK", peakHoursDesc: "Sabah ve akşam, kayalık kıyı",
        tempRange: { min: 14, opt: 20, max: 26 },
        seasons: { winter: 0.60, spring: 0.55, summer: 0.45, autumn: 0.70 },
        activity: "DAWN_DUSK",
        pressureSensitivity: 0.5,
        wavePref: 0.6,
        clarityPref: "TURBID",
        currentPref: 0.4,
        salinityPref: "ANY",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 1, opt: 15, max: 60 },
        advice: { bait: "Yengeç, Midye, Mamun", lure: "Silikon Karides", rig: "Şeytan Oltası, Dip Takımı", hook: "2 - 6" },
        legalSize: "18 cm",
        note: "Sivri burunlu karagöz. Köpüklü su sever."
    },
    "sargoz": {
        name: "Sargoz", nameEn: "White Seabream", icon: "🐟", scientificName: "Diplodus sargus",
        photoId: 19,
        category: "KIYI",
        peakHours: "DAWN_DUSK", peakHoursDesc: "Sabah ve akşam suyu, kayalık kıyı",
        tempRange: { min: 14, opt: 20, max: 26 },
        seasons: { winter: 0.65, spring: 0.55, summer: 0.40, autumn: 0.75 },
        activity: "DAWN_DUSK",
        pressureSensitivity: 0.6,
        wavePref: 0.8,
        clarityPref: "TURBID",
        currentPref: 0.5,
        salinityPref: "MEDIUM",
        planktonPref: "MEDIUM",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 1, opt: 15, max: 50 },
        advice: { bait: "Midye, Yengeç, Mamun", lure: "Silikon", rig: "Şeytan Oltası, Dip", hook: "1 - 4" },
        legalSize: "23 cm",
        note: "Karagözün büyük akrabası. Köpüklü, dalgalı su sever."
    },
    "hani": {
        name: "Hani/Hanos", nameEn: "Comber", icon: "🐟", scientificName: "Serranus cabrilla",
        photoId: 38,
        category: "DIP_KIYI",
        peakHours: "DAY", peakHoursDesc: "Gündüz, kayalık dip",
        tempRange: { min: 12, opt: 18, max: 24 },
        seasons: { winter: 0.55, spring: 0.65, summer: 0.70, autumn: 0.60 },
        activity: "DAY",
        pressureSensitivity: 0.4,
        wavePref: 0.4,
        clarityPref: "MODERATE",
        currentPref: 0.3,
        salinityPref: "MEDIUM",
        regions: ["EGE", "AKDENİZ", "MARMARA", "KARADENİZ"],
        depth: { min: 2, opt: 25, max: 90 },
        advice: { bait: "Karides, Kurt, Midye", lure: "LRF Silikon", rig: "LRF, Dip Takımı", hook: "6 - 10" },
        adviceEn: { bait: "Shrimp, Worm, Mussel", lure: "LRF Soft Plastic", rig: "LRF, Bottom Rig", hook: "6 - 10" },
        legalSize: "Yok",
        legalSizeEn: "None",
        note: "Küçük ama lezzetli. Kayalık dip sever. LRF ile eğlenceli."
    },
    "sarikulak": {
        name: "Sarıkulak Kefal", nameEn: "Golden Grey Mullet", icon: "🐟", scientificName: "Chelon auratus",
        photoId: 45,
        category: "LAGUN",
        peakHours: "DAY", peakHoursDesc: "Sabah erken, lagün ve kıyı",
        tempRange: { min: 10, opt: 18, max: 26 },
        seasons: { winter: 0.45, spring: 0.70, summer: 0.80, autumn: 0.60 },
        activity: "DAY",
        pressureSensitivity: 0.4,
        wavePref: 0.3,
        clarityPref: "TURBID",
        currentPref: 0.3,
        salinityPref: "LOW",  // Lagün türü — düşük/acı tuzlu suyu tercih eder
        regions: ["MARMARA", "EGE", "AKDENİZ", "KARADENİZ"],
        depth: { min: 0, opt: 5, max: 20 },
        advice: { bait: "Ekmek, Kıbrıs Sarma", lure: "Yok", rig: "Kıbrıs Takımı, Şamandıralı", hook: "6 - 10" },
        legalSize: "20 cm",
        note: "Solungaç kapağındaki sarı lekeyle tanınır. Lagün sever."
    },
    // ═══════════════════════════════════════════════════════════════════════════
    // YENİ EKLENEN TÜRLER - v2.4
    // ═══════════════════════════════════════════════════════════════════════════
    "tranca": {
        name: "Trança", nameEn: "Pink Dentex", icon: "🐟", scientificName: "Dentex gibbosus",
        photoId: 49,
        category: "DIP_DERIN",
        shoreMonths: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAY", peakHoursDesc: "Gündüz, derin su",
        tempRange: { min: 16, opt: 21, max: 26 },
        seasons: { winter: 0.40, spring: 0.70, summer: 0.85, autumn: 0.75 },
        activity: "DAY",
        pressureSensitivity: 0.7,
        wavePref: 0.4,
        clarityPref: "CLEAR",
        currentPref: 0.5,
        salinityPref: "ANY",
        planktonPref: "LOW",
        regions: ["EGE", "AKDENİZ"],
        depth: { min: 30, opt: 60, max: 100 },
        advice: { bait: "Canlı Kalamar, Teke", lure: "Jig, Inchiku", rig: "Jig Takımı, Derin Dip", hook: "2/0 - 4/0" },
        legalSize: "25 cm",
        note: "Derin suyun kralı. Jigging ile efsanevi av. Sert direnç gösterir."
    },
    "subye": {
        name: "Sübye", nameEn: "Common Cuttlefish", icon: "🦑", scientificName: "Sepia officinalis",
        photoId: 48,
        category: "KALAMAR",
        peakHours: "NIGHT", peakHoursDesc: "Gece, kıyı yakını",
        tempRange: { min: 14, opt: 18, max: 24 },
        seasons: { winter: 0.75, spring: 0.85, summer: 0.50, autumn: 0.90 },
        activity: "NIGHT",
        pressureSensitivity: 0.5,
        wavePref: 0.3,
        clarityPref: "CLEAR",
        currentPref: 0.3,
        salinityPref: "HIGH",
        planktonPref: "LOW",
        moonPref: "bright",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 2, opt: 10, max: 25 },
        advice: { bait: "Kalamar Zokası", lure: "Egi 2.5-3.5", rig: "Eging Takımı", hook: "Zoka" },
        legalSize: "Yok",
        note: "Sonbahar favorisi. Eging ile keyifli av. Gece lambası çeker."
    },
    "sarikuyruk": {
        name: "Sarıkuyruk", nameEn: "Greater Amberjack", icon: "🐟", scientificName: "Seriola dumerili",
        photoId: 50,
        category: "AVCI",
        shoreMonths: [6, 7, 8, 9], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAY", peakHoursDesc: "Sabah/Akşam, açık su",
        tempRange: { min: 18, opt: 24, max: 28 },
        seasons: { winter: 0.30, spring: 0.60, summer: 0.90, autumn: 0.80 },
        activity: "DAY",
        pressureSensitivity: 0.6,
        wavePref: 0.5,
        clarityPref: "CLEAR",
        currentPref: 0.6,
        salinityPref: "MEDIUM",
        moonPref: "dark",
        regions: ["AKDENİZ", "EGE"],
        depth: { min: 10, opt: 35, max: 70 },
        advice: { bait: "Canlı Zargana", lure: "Jig 60-150g, Popper", rig: "Jigging Setup", hook: "3/0 - 5/0" },
        legalSize: "45 cm",
        note: "Güçlü game fish. Jigging'in yıldızı. Acımasız direnç gösterir."
    },
    "granyoz": {
        name: "Granyoz (Sarıağız)", nameEn: "Meagre", icon: "🐟", scientificName: "Argyrosomus regius",
        photoId: 10,
        category: "AVCI",
        shoreMonths: [5, 6, 7, 8, 9], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "NIGHT", peakHoursDesc: "Gece ve alacakaranlık",
        tempRange: { min: 16, opt: 21, max: 26 },
        seasons: { winter: 0.35, spring: 0.65, summer: 0.80, autumn: 0.70 },
        activity: "NIGHT",
        pressureSensitivity: 0.7,
        wavePref: 0.4,
        clarityPref: "MODERATE",
        currentPref: 0.5,
        salinityPref: "HIGH",
        regions: ["EGE", "AKDENİZ"],
        depth: { min: 5, opt: 25, max: 60 },
        advice: { bait: "Canlı Teke, Sübye", lure: "Silikon 12-18cm", rig: "Dip, Spin", hook: "2/0 - 4/0" },
        legalSize: "42 cm",
        note: "Gece avcısı dev. 50kg'a ulaşabilir. Ses çıkarır (davul balığı)."
    },
    "lambuga": {
        name: "Lambuga (Mahi Mahi)", nameEn: "Common Dolphinfish", icon: "🐟", scientificName: "Coryphaena hippurus",
        photoId: 83,
        category: "AVCI",
        shoreMonths: [], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAY", peakHoursDesc: "Gündüz, yüzey",
        tempRange: { min: 21, opt: 26, max: 30 },
        seasons: { winter: 0.15, spring: 0.40, summer: 0.95, autumn: 0.70 },
        activity: "DAY",
        pressureSensitivity: 0.4,
        wavePref: 0.4,
        clarityPref: "CLEAR",
        currentPref: 0.5,
        salinityPref: "HIGH",
        planktonPref: "HIGH",
        moonPref: "dark",
        sstTrendPref: "warming",
        regions: ["AKDENİZ", "EGE"],
        depth: { min: 0, opt: 10, max: 35 },
        advice: { bait: "Küçük balık", lure: "Popper, Sahte Balık", rig: "Trolling, Spin", hook: "2/0 - 4/0" },
        legalSize: "Yok",
        note: "Tropikal güzellik. Yüzen nesnelerin altında bulunur. Hızlı büyür."
    },
    "uskumru": {
        name: "Uskumru", nameEn: "Atlantic Mackerel", icon: "🐟", scientificName: "Scomber scombrus",
        photoId: 27,
        category: "SÜRÜ",
        shoreMonths: [], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAY", peakHoursDesc: "Sabah/Akşam",
        tempRange: { min: 10, opt: 15, max: 20 },
        seasons: { winter: 0.60, spring: 0.85, summer: 0.40, autumn: 0.75 },
        monthlyActivity: [0.55, 0.5, 0.7, 0.85, 0.9, 0.4, 0.3, 0.35, 0.6, 0.8, 0.75, 0.6],
        activity: "DAY",
        pressureSensitivity: 0.5,
        wavePref: 0.4,
        clarityPref: "CLEAR",
        currentPref: 0.5,
        salinityPref: "HIGH",
        planktonPref: "HIGH",
        sstTrendPref: "any",
        regions: ["MARMARA", "EGE"],
        depth: { min: 5, opt: 20, max: 50 },
        advice: { bait: "Çapari", lure: "Küçük Kaşık", rig: "Çapari Takımı", hook: "6 - 10" },
        legalSize: "18 cm",
        note: "Serin su sever. Sürü halinde. Lezzetli ve bereketli av."
    },
    "kolyoz": {
        name: "Kolyoz", nameEn: "Chub Mackerel", icon: "🐟", scientificName: "Scomber japonicus",
        photoId: 28,
        category: "SÜRÜ",
        shoreMonths: [3, 4, 5, 8, 9, 10], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAY", peakHoursDesc: "Gündüz",
        tempRange: { min: 15, opt: 22, max: 27 },
        seasons: { winter: 0.40, spring: 0.70, summer: 0.85, autumn: 0.75 },
        monthlyActivity: [0.35, 0.3, 0.55, 0.7, 0.85, 0.9, 0.9, 0.85, 0.8, 0.7, 0.5, 0.4],
        migrationBonus: {
        "EGE":       { months: [4,5,6,7,8], bonus: 0.20 },
        "AKDENİZ":   { months: [3,4,5],    bonus: 0.15 }
    },
        activity: "DAY",
        pressureSensitivity: 0.5,
        wavePref: 0.4,
        clarityPref: "CLEAR",
        currentPref: 0.5,
        salinityPref: "MEDIUM",
        planktonPref: "HIGH",
        sstTrendPref: "warming",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 5, opt: 25, max: 50 },
        advice: { bait: "Çapari", lure: "Kaşık", rig: "Çapari Takımı, Spin", hook: "6 - 10" },
        legalSize: "18 cm",
        note: "Uskumruya benzer ama daha sıcak su sever. Yaz mevsimi balığı."
    },
    "sarpa": {
        name: "Sarpa (Salpa)", nameEn: "Salema", icon: "🐟", scientificName: "Sarpa salpa",
        photoId: 22,
        category: "KAYALIK",
        peakHours: "DAY", peakHoursDesc: "Gündüz, sığ",
        tempRange: { min: 16, opt: 22, max: 28 },
        seasons: { winter: 0.40, spring: 0.70, summer: 0.85, autumn: 0.65 },
        activity: "DAY",
        pressureSensitivity: 0.3,
        wavePref: 0.3,
        clarityPref: "CLEAR",
        currentPref: 0.2,
        salinityPref: "MEDIUM",
        regions: ["EGE", "AKDENİZ"],
        depth: { min: 1, opt: 5, max: 15 },
        advice: { bait: "Ekmek, Yosun", lure: "Yok", rig: "Şamandıralı", hook: "10 - 14" },
        legalSize: "Yok",
        note: "Otobur balık. Ekmekle kolay avlanır. Halüsinasyon yapabilir (dikkat!)."
    },
    "iskatarya": {
        name: "İskatarya", nameEn: "Atlantic Chub Mackerel", icon: "🐟", scientificName: "Scomber colias",
        photoId: 73,
        category: "PELAJIK",
        shoreMonths: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAY", peakHoursDesc: "Sabah erken ve akşamüstü, yüzey",
        tempRange: { min: 15, opt: 20, max: 26 },
        seasons: { winter: 0.20, spring: 0.75, summer: 0.90, autumn: 0.80 },
        activity: "DAY",
        pressureSensitivity: 0.4,
        wavePref: 0.4,
        clarityPref: "MEDIUM",
        currentPref: 0.5,
        salinityPref: "MEDIUM",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 0, opt: 25, max: 200 },
        advice: { bait: "Çapari, Küçük balık", lure: "Tüylü iğne, Kaşık", rig: "Çoklu iğneli", hook: "8 - 12" },
        legalSize: "18 cm",
        note: "Kolyoza benzer ama karnında noktalı desen ayırt eder. Sürü halinde göç eder, sabah erken yüzeyde aktif."
    },
    "lokum": {
        name: "Lokum Balığı", nameEn: "Silver Biddy", icon: "🐟", scientificName: "Sillago sihama",
        photoId: 85,
        category: "KUMSAL",
        shoreMonths: [6, 7, 8], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAY", peakHoursDesc: "Gündüz, kumlu sığ su ve kıyı şeridi",
        tempRange: { min: 20, opt: 26, max: 30 },
        seasons: { winter: 0.10, spring: 0.50, summer: 1.00, autumn: 0.70 },
        activity: "DAY",
        pressureSensitivity: 0.3,
        wavePref: 0.2,
        clarityPref: "HIGH",
        currentPref: 0.3,
        salinityPref: "MEDIUM",
        regions: ["EGE", "AKDENİZ", "KKTC"],
        depth: { min: 0, opt: 10, max: 70 },
        advice: { bait: "Karides, Solucan, Deniz kurdu", lure: "Küçük jig", rig: "Hafif dip", hook: "8 - 12" },
        legalSize: "15 cm",
        note: "Lesepsiyen istilacı tür. Kumlu ve çamurlu sığ sularda sürü halinde. Yaz aylarında Akdeniz ve Ege kıyılarında çok yaygın. Dipte karides ve solucanla kolayca avlanır."
    },
    "muren": {
        name: "Müren", nameEn: "Mediterranean Moray", icon: "🐍", scientificName: "Muraena helena",
        photoId: 54,
        category: "KAYALIK",
        peakHours: "NIGHT", peakHoursDesc: "Gece, kayalık",
        tempRange: { min: 18, opt: 23, max: 28 },
        seasons: { winter: 0.35, spring: 0.55, summer: 0.80, autumn: 0.70 },
        activity: "NIGHT",
        pressureSensitivity: 0.4,
        wavePref: 0.3,
        clarityPref: "MODERATE",
        currentPref: 0.3,
        salinityPref: "HIGH",
        regions: ["EGE", "AKDENİZ"],
        depth: { min: 2, opt: 15, max: 40 },
        advice: { bait: "Balık Kafası, Kalamar", lure: "Yok", rig: "Ağır Dip", hook: "4/0 - 6/0" },
        legalSize: "Yok",
        note: "Keskin dişli! Dikkatli tutun. Gece avcısı. Kayalık kovuklarda yaşar."
    },
    "migri": {
        name: "Mığrı (Deniz Yılanı)", nameEn: "European Conger", icon: "🐍", scientificName: "Conger conger",
        photoId: 53,
        category: "DIP_DERIN",
        shoreMonths: [], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "NIGHT", peakHoursDesc: "Gece, kayalık dip",
        tempRange: { min: 12, opt: 17, max: 24 },
        seasons: { winter: 0.55, spring: 0.65, summer: 0.70, autumn: 0.75 },
        activity: "NIGHT",
        pressureSensitivity: 0.5,
        wavePref: 0.4,
        clarityPref: "TURBID",
        currentPref: 0.4,
        salinityPref: "HIGH",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 5, opt: 25, max: 60 },
        advice: { bait: "Balık Eti, Kalamar", lure: "Yok", rig: "Ağır Dip", hook: "4/0 - 8/0" },
        legalSize: "Yok",
        note: "Dev olabilir (2m+). Gece avcısı. Kayalık kovukları sever."
    },
    "zurna": {
        name: "Zurna", nameEn: "European Barracuda", icon: "🐟", scientificName: "Sphyraena sphyraena",
        photoId: 52,
        category: "AVCI",
        shoreMonths: [6, 7, 8, 9], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAY", peakHoursDesc: "Gündüz, yüzey",
        tempRange: { min: 18, opt: 24, max: 28 },
        seasons: { winter: 0.25, spring: 0.55, summer: 0.90, autumn: 0.70 },
        activity: "DAY",
        pressureSensitivity: 0.4,
        wavePref: 0.4,
        clarityPref: "CLEAR",
        currentPref: 0.5,
        salinityPref: "MEDIUM",
        regions: ["EGE", "AKDENİZ"],
        depth: { min: 0, opt: 5, max: 20 },
        advice: { bait: "İpek", lure: "Küçük Sahte Balık", rig: "Spin, LRF", hook: "6 - 2" },
        legalSize: "Yok",
        note: "Hızlı avcı. Yüzeyde sürü halinde. Lüfer/Kofana yemi olarak kullanılır."
    },
    "barakuda": {
        name: "Baraküda", nameEn: "Yellowmouth Barracuda", icon: "🐟", scientificName: "Sphyraena viridensis",
        photoId: 51,
        category: "AVCI",
        shoreMonths: [6, 7, 8, 9], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "CREPUSCULAR", peakHoursDesc: "Alacakaranlık ve gece",
        tempRange: { min: 18, opt: 24, max: 29 },
        seasons: { winter: 0.25, spring: 0.50, summer: 0.85, autumn: 0.70 },
        activity: "NIGHT",
        pressureSensitivity: 0.5,
        wavePref: 0.4,
        clarityPref: "CLEAR",
        currentPref: 0.5,
        salinityPref: "HIGH",
        planktonPref: "HIGH",
        moonPref: "dark",
        sstTrendPref: "warming",
        regions: ["AKDENİZ", "EGE"],
        depth: { min: 2, opt: 15, max: 40 },
        advice: { bait: "Yapay tercih", lure: "Uzun Sahte Balık", rig: "Spin", hook: "2/0 - 4/0" },
        legalSize: "Yok",
        note: "Keskin dişli! Çelik tel şart. Alacakaranlıkta agresif avlanır."
    },
    "kirlangic": {
        name: "Kırlangıç", nameEn: "Tub Gurnard", icon: "🐟", scientificName: "Chelidonichthys lucerna",
        photoId: 59,
        category: "DIP_KIYI",
        peakHours: "DAY", peakHoursDesc: "Gündüz, kumlu dip",
        tempRange: { min: 12, opt: 17, max: 22 },
        seasons: { winter: 0.60, spring: 0.75, summer: 0.65, autumn: 0.70 },
        activity: "DAY",
        pressureSensitivity: 0.5,
        wavePref: 0.4,
        clarityPref: "MODERATE",
        currentPref: 0.4,
        salinityPref: "HIGH",
        regions: ["EGE", "AKDENİZ", "MARMARA", "KARADENİZ"],
        depth: { min: 15, opt: 35, max: 80 },
        advice: { bait: "Teke, İstavrit", lure: "Jig", rig: "Dip, Jig", hook: "2 - 2/0" },
        legalSize: "Yok",
        note: "Renkli yüzgeçlerle uçar gibi yüzer. Lezzetli eti var."
    },
    "dil_baligi": {
        name: "Dil Balığı", nameEn: "Common Sole", icon: "🐟", scientificName: "Solea solea",
        photoId: 42,
        category: "DIP_KIYI",
        peakHours: "NIGHT", peakHoursDesc: "Gece, kumlu dip",
        tempRange: { min: 12, opt: 18, max: 26 },
        seasons: { winter: 0.55, spring: 0.70, summer: 0.75, autumn: 0.80 },
        activity: "NIGHT",
        pressureSensitivity: 0.4,
        wavePref: 0.3,
        clarityPref: "TURBID",
        currentPref: 0.3,
        salinityPref: "ANY",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 3, opt: 15, max: 40 },
        advice: { bait: "Boru Kurdu", lure: "Yok", rig: "Dip", hook: "6 - 10" },
        legalSize: "20 cm",
        note: "Gece aktif, gündüz kuma gömülür. Boru kurdu en iyi yem."
    },
    "gelincik": {
        name: "Gelincik", nameEn: "Shore Rockling", icon: "🐟", scientificName: "Gaidropsarus mediterraneus",
        photoId: 55,
        category: "KAYALIK",
        peakHours: "NIGHT", peakHoursDesc: "Gece, kayalık",
        tempRange: { min: 10, opt: 16, max: 24 },
        seasons: { winter: 0.65, spring: 0.70, summer: 0.55, autumn: 0.75 },
        activity: "NIGHT",
        pressureSensitivity: 0.4,
        wavePref: 0.3,
        clarityPref: "TURBID",
        currentPref: 0.3,
        salinityPref: "MEDIUM",
        regions: ["EGE", "AKDENİZ", "MARMARA", "KARADENİZ"],
        depth: { min: 3, opt: 15, max: 40 },
        advice: { bait: "Karides, Balık eti", lure: "Yok", rig: "Dip", hook: "4 - 8" },
        legalSize: "Yok",
        note: "Yılan gibi görünür. Gece kayalık aralarında avlanır."
    },
    "vatoz": {
        name: "Vatoz", nameEn: "Common Stingray", icon: "🦈", scientificName: "Dasyatis pastinaca",
        photoId: 58,
        category: "DIP_KIYI",
        peakHours: "NIGHT", peakHoursDesc: "Gece, kumlu dip",
        tempRange: { min: 12, opt: 18, max: 26 },
        seasons: { winter: 0.40, spring: 0.65, summer: 0.80, autumn: 0.70 },
        activity: "NIGHT",
        pressureSensitivity: 0.5,
        wavePref: 0.3,
        clarityPref: "TURBID",
        currentPref: 0.3,
        salinityPref: "ANY",
        regions: ["EGE", "AKDENİZ", "MARMARA", "KARADENİZ"],
        depth: { min: 2, opt: 20, max: 60 },
        advice: { bait: "Balık Eti", lure: "Yok", rig: "Ağır Dip", hook: "4/0 - 6/0" },
        legalSize: "Yok",
        note: "DİKKAT: Zehirli dikeni var! Tutarken çok dikkatli olun."
    },
    "cutre": {
        name: "Çütre (Tetik)", nameEn: "Grey Triggerfish", icon: "🐟", scientificName: "Balistes capriscus",
        photoId: 72,
        category: "KAYALIK",
        shoreMonths: [5, 6, 7, 8, 9], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAY", peakHoursDesc: "Gündüz, kayalık",
        tempRange: { min: 18, opt: 24, max: 28 },
        seasons: { winter: 0.25, spring: 0.50, summer: 0.85, autumn: 0.65 },
        activity: "DAY",
        pressureSensitivity: 0.4,
        wavePref: 0.3,
        clarityPref: "CLEAR",
        currentPref: 0.3,
        salinityPref: "ANY",
        regions: ["EGE", "AKDENİZ"],
        depth: { min: 3, opt: 15, max: 40 },
        advice: { bait: "Karides, Midye", lure: "Yok", rig: "Dip", hook: "4 - 8" },
        legalSize: "Yok",
        note: "Sert çeneli, iğneyi koparır. Güçlü bir tetik mekanizması var."
    },
    "kurbaga": {
        name: "Kurbağa Balığı (Trakonya)", nameEn: "Atlantic Stargazer", icon: "🐟", scientificName: "Uranoscopus scaber",
        photoId: 79,
        category: "DIP_KIYI",
        peakHours: "DAWN_DUSK", peakHoursDesc: "Alacakaranlık ve gündüz — kuma gömülü puskuru avcısı",
        tempRange: { min: 12, opt: 18, max: 26 },
        seasons: { winter: 0.50, spring: 0.65, summer: 0.75, autumn: 0.70 },
        activity: "DAWN_DUSK",  // BİYOLOJİK DÜZELTİ: Uranoscopus scaber gündüz-alacakaranlık tuzak avcısıdır, gece gezen değil
        pressureSensitivity: 0.4,
        wavePref: 0.3,
        clarityPref: "TURBID",
        currentPref: 0.3,
        salinityPref: "HIGH",
        regions: ["EGE", "AKDENİZ", "MARMARA", "KARADENİZ"],
        depth: { min: 3, opt: 20, max: 50 },
        advice: { bait: "Balık Eti", lure: "Yok", rig: "Dip", hook: "2 - 4" },
        legalSize: "Yok",
        note: "DİKKAT: Zehirli dikenleri var! Kuma gömülü bekler."
    },
    "fener": {
        name: "Fener Balığı", nameEn: "Anglerfish", icon: "🐟", scientificName: "Lophius piscatorius",
        photoId: 80,
        category: "DIP_DERIN",
        shoreMonths: [], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAY", peakHoursDesc: "Gündüz, derin dip",
        tempRange: { min: 10, opt: 14, max: 20 },
        seasons: { winter: 0.70, spring: 0.75, summer: 0.55, autumn: 0.65 },
        activity: "DAY",
        pressureSensitivity: 0.5,
        wavePref: 0.4,
        clarityPref: "TURBID",
        currentPref: 0.4,
        salinityPref: "ANY",
        regions: ["EGE", "AKDENİZ", "MARMARA", "KARADENİZ"],
        depth: { min: 20, opt: 80, max: 250 },
        advice: { bait: "Balık Eti", lure: "Yok", rig: "Ağır Dip", hook: "4/0 - 8/0" },
        legalSize: "30 cm",
        note: "Çirkin ama çok lezzetli. Derin suda yaşar. Kuyruk eti makbul."
    },
    "hamsi": {
        name: "Hamsi", nameEn: "European Anchovy", icon: "🐟", scientificName: "Engraulis encrasicolus",
        photoId: 32,
        category: "SÜRÜ",
        shoreMonths: [10, 11, 0, 1], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAY", peakHoursDesc: "Gündüz, sürü halinde",
        tempRange: { min: 8, opt: 12, max: 18 },
        seasons: { winter: 0.95, spring: 0.50, summer: 0.20, autumn: 0.70 },
        monthlyActivity: [0.95, 0.9, 0.55, 0.4, 0.25, 0.15, 0.15, 0.2, 0.45, 0.7, 0.9, 0.95],
        migrationBonus: {
        "KARADENİZ": { months: [9,10,11,0], bonus: 0.35 },
        "MARMARA":   { months: [10,11,0],  bonus: 0.25 }
    },
        activity: "DAY",
        pressureSensitivity: 0.4,
        wavePref: 0.4,
        clarityPref: "MODERATE",
        currentPref: 0.5,
        salinityPref: "ANY",
        planktonPref: "HIGH",
        moonPref: "bright",
        sstTrendPref: "cooling",
        regions: ["KARADENİZ", "MARMARA"],
        depth: { min: 5, opt: 25, max: 60 },
        advice: { bait: "Çapari", lure: "İnce Çapari", rig: "Surf, Çapari", hook: "10 - 14" },
        legalSize: "9 cm",
        note: "Karadeniz'in simgesi. Kış aylarında bollaşır. Tava için ideal."
    },
    "aslan_baligi": {
        name: "Aslan Balığı", nameEn: "Devil Firefish", icon: "🦁", scientificName: "Pterois miles",
        photoId: 71,
        category: "İSTİLACI",
        peakHours: "CREPUSCULAR", peakHoursDesc: "Alacakaranlık",
        tempRange: { min: 18, opt: 25, max: 30 },
        seasons: { winter: 0.40, spring: 0.65, summer: 0.85, autumn: 0.75 },
        activity: "NIGHT",
        pressureSensitivity: 0.4,
        wavePref: 0.3,
        clarityPref: "CLEAR",
        currentPref: 0.3,
        salinityPref: "LOW",
        regions: ["AKDENİZ", "EGE"],
        depth: { min: 2, opt: 20, max: 50 },
        advice: { bait: "Karides, Küçük balık", lure: "Micro Jig", rig: "LRF, Dip", hook: "4 - 8" },
        legalSize: "Yok",
        note: "⚠️ İSTİLACI TÜR! ZEHİRLİ dikenleri var. Avladığınızda öldürün."
    },
    "balon_baligi": {
        name: "Balon Balığı", nameEn: "Silver-cheeked Toadfish", icon: "🐡", scientificName: "Lagocephalus sceleratus",
        photoId: 70,
        category: "İSTİLACI",
        peakHours: "DAY", peakHoursDesc: "Gündüz",
        tempRange: { min: 18, opt: 26, max: 32 },
        seasons: { winter: 0.35, spring: 0.60, summer: 0.90, autumn: 0.70 },
        activity: "DAY",
        pressureSensitivity: 0.3,
        wavePref: 0.3,
        clarityPref: "CLEAR",
        currentPref: 0.3,
        salinityPref: "HIGH",
        regions: ["AKDENİZ", "EGE"],
        depth: { min: 1, opt: 20, max: 60 },
        advice: { bait: "Her yemi yer", lure: "Yok", rig: "Dip", hook: "2 - 6" },
        legalSize: "Yok",
        note: "⚠️ ÖLDÜRÜCÜ ZEHİRLİ! Kesinlikle yemeyin. İstilacı tür, avladığınızda öldürün."
    },
    // ═══════════════════════════════════════════════════════════════════
    // YENİ EKLENEN BALIKLAR
    // ═══════════════════════════════════════════════════════════════════
    "isparoz": {
        name: "İsparoz", nameEn: "Annular Seabream", icon: "🐟", scientificName: "Diplodus annularis",
        photoId: 21,
        category: "DIP_KIYI",
        peakHours: "DAY", peakHoursDesc: "Gündüz, sığ kayalık",
        tempRange: { min: 12, opt: 18, max: 26 },
        seasons: { winter: 0.50, spring: 0.75, summer: 0.85, autumn: 0.70 },
        activity: "DAY",
        pressureSensitivity: 0.4,
        wavePref: 0.4,
        clarityPref: "MODERATE",
        currentPref: 0.3,
        salinityPref: "HIGH",
        planktonPref: "MEDIUM",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 1, opt: 15, max: 50 },
        advice: { bait: "Ekmek, Kurt, Karides", lure: "Yok", rig: "Çapari, Dip", hook: "10 - 14" },
        legalSize: "Yok",
        note: "Sürü halinde gezer. Ekmek ile bereketle avlanır."
    },
    "yazili_orkinos": {
        name: "Yazılı Orkinos", nameEn: "Little Tunny", icon: "🐟", scientificName: "Euthynnus alletteratus",
        photoId: 29,
        category: "PELAJIK",
        shoreMonths: [], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAY", peakHoursDesc: "Sabah-Öğlen, açık deniz",
        tempRange: { min: 18, opt: 24, max: 30 },
        seasons: { winter: 0.30, spring: 0.60, summer: 0.90, autumn: 0.70 },
        monthlyActivity: [0.25, 0.25, 0.45, 0.6, 0.75, 0.9, 0.95, 0.9, 0.75, 0.65, 0.45, 0.3],
        migrationBonus: {
        "AKDENİZ":   { months: [4,5,6,7,8], bonus: 0.25 },
        "EGE":       { months: [5,6,7],    bonus: 0.20 }
    },
        activity: "DAY",
        pressureSensitivity: 0.5,
        wavePref: 0.5,
        clarityPref: "CLEAR",
        currentPref: 0.6,
        salinityPref: "MEDIUM",
        planktonPref: "HIGH",
        sstTrendPref: "warming",
        regions: ["EGE", "AKDENİZ", "MARMARA"],
        depth: { min: 5, opt: 50, max: 200 },
        advice: { bait: "Canlı balık, Sardalya", lure: "Rapala, Metal Jig", rig: "Trolling", hook: "2/0 - 4/0" },
        legalSize: "25 cm",
        note: "Hızlı ve güçlü. Trolling ile avlanır."
    },
    "palamut": {
        name: "Palamut", nameEn: "Atlantic Bonito", icon: "🐟", scientificName: "Sarda sarda",
        photoId: 25,
        category: "PELAJIK",
        shoreMonths: [8, 9, 10], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAWN_DUSK", peakHoursDesc: "Sabah-Akşam",
        tempRange: { min: 12, opt: 18, max: 24 },
        seasons: { winter: 0.50, spring: 0.65, summer: 0.55, autumn: 0.90 },
        monthlyActivity: [0.45, 0.4, 0.55, 0.65, 0.7, 0.55, 0.5, 0.55, 0.75, 0.95, 0.85, 0.55],
        migrationBonus: {
        "KARADENİZ": { months: [4,5,6,7],  bonus: 0.30 },
        "MARMARA":   { months: [9,10],     bonus: 0.40 },
        "EGE":       { months: [3,4,10,11],bonus: 0.20 }
    },
        activity: "CREPUSCULAR",
        pressureSensitivity: 0.6,
        wavePref: 0.5,
        clarityPref: "MODERATE",
        currentPref: 0.5,
        salinityPref: "MEDIUM",
        planktonPref: "HIGH",
        moonPref: "dark",
        sstTrendPref: "cooling",
        regions: ["MARMARA", "KARADENİZ", "EGE"],
        depth: { min: 5, opt: 30, max: 100 },
        advice: { bait: "İstavrit, Sardalya, Sahte Yem", lure: "Tüylü Çapari, Kaşık, Kaplamalı Jig", rig: "Çapari, Trolling, Sırtı", hook: "1/0 - 3/0" },
        legalSize: "25 cm",
        note: "Sonbahar balığı. Boğazlarda bol bulunur. Yamyamlık eğilimi — sürüye metal atar."
    },
    "torik": {
        name: "Torik", nameEn: "Atlantic Bonito (Large)", icon: "🐟", scientificName: "Sarda sarda",
        photoId: 26,
        category: "PELAJIK",
        shoreMonths: [], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAWN_DUSK", peakHoursDesc: "Sabah-Akşam, derin",
        tempRange: { min: 10, opt: 16, max: 22 },
        seasons: { winter: 0.70, spring: 0.50, summer: 0.30, autumn: 0.65 },
        monthlyActivity: [0.6, 0.55, 0.5, 0.55, 0.5, 0.3, 0.25, 0.3, 0.55, 0.75, 0.7, 0.65],
        activity: "CREPUSCULAR",
        pressureSensitivity: 0.6,
        wavePref: 0.6,
        clarityPref: "MODERATE",
        currentPref: 0.6,
        salinityPref: "ANY",
        planktonPref: "HIGH",
        moonPref: "dark",
        sstTrendPref: "cooling",
        regions: ["MARMARA", "KARADENİZ", "EGE"],
        depth: { min: 20, opt: 60, max: 150 },
        advice: { bait: "Canlı balık", lure: "Büyük Rapala, Jig", rig: "Trolling", hook: "3/0 - 5/0" },
        legalSize: "Yok",
        note: "Palamutun büyüğü. Kış aylarında daha derin."
    },
    "cinekop": {
        name: "Çinekop", nameEn: "Baby Bluefish", icon: "🐟", scientificName: "Pomatomus saltatrix (juv.)",
        photoId: 31,
        category: "PELAJIK",
        shoreMonths: [7, 8, 9, 10], // kıyıya yaklaşma ayları (0=Ocak)
        peakHours: "DAWN_DUSK", peakHoursDesc: "Sabah-Akşam",
        tempRange: { min: 14, opt: 20, max: 26 },
        seasons: { winter: 0.35, spring: 0.60, summer: 0.80, autumn: 0.90 },
        monthlyActivity: [0.3, 0.25, 0.45, 0.6, 0.75, 0.85, 0.9, 0.95, 0.9, 0.8, 0.55, 0.35],
        activity: "CREPUSCULAR",
        pressureSensitivity: 0.5,
        wavePref: 0.5,
        clarityPref: "MODERATE",
        currentPref: 0.4,
        salinityPref: "ANY",
        planktonPref: "HIGH",
        moonPref: "dark",
        sstTrendPref: "cooling",
        regions: ["MARMARA", "KARADENİZ", "EGE", "AKDENİZ"],
        depth: { min: 2, opt: 15, max: 40 },
        advice: { bait: "Çaça, Hamsi", lure: "Küçük Kaşık", rig: "Spin, Çapari", hook: "4 - 8" },
        legalSize: "20 cm",
        note: "Lüferin yavrusu. Sürü halinde avlanır."
    },
